// Generated by github.com/sunfmin/goapigen
// DO NOT EDIT

#import <Foundation/Foundation.h>

@interface Error : NSObject
@end

@interface Validated : NSObject
@end


// --- Organization ---
@interface Organization : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * Name;
@property (nonatomic, strong) NSString * QortexURL;
@property (nonatomic, strong) NSString * Summary;
@property (nonatomic, strong) NSString * LogoURL;
@property (nonatomic, strong) NSString * Address;
@property (nonatomic, strong) NSString * Phone;
@property (nonatomic, strong) NSString * Website;
@property (nonatomic, strong) NSArray * Domains;
@property (nonatomic, assign) BOOL RestrictSubscriptionMail;
@end


// === Interfaces ===


// --- OrganizationInfoParams ---
@interface AuthUserServiceOrganizationInfoParams : NSObject
@property (nonatomic, strong) NSString * OrgId;
@end

// --- OrganizationInfoResults ---
@interface AuthUserServiceOrganizationInfoResults : NSObject
@property (nonatomic, strong) Organization * Org;
@property (nonatomic, strong) NSError * Err;
@end


@interface AuthUserService : NSObject
@property (nonatomic, strong) NSString * Session;


- (AuthUserServiceOrganizationInfoResults *) OrganizationInfo:(NSString *)orgId;
@end


// --- GetSessionParams ---
@interface GlobalGetSessionParams : NSObject
@property (nonatomic, strong) NSString * Email;
@property (nonatomic, strong) NSString * Password;
@end

// --- GetSessionResults ---
@interface GlobalGetSessionResults : NSObject
@property (nonatomic, strong) NSString * Session;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end


@interface Global : NSObject

- (GlobalGetSessionResults *) GetSession:(NSString *)email password:(NSString *)password;

- (AuthUserService *) GetAuthUserService:(NSString *)session;
@end

