// Generated by github.com/sunfmin/goapigen
// DO NOT EDIT

#import <Foundation/Foundation.h>

@interface Error : NSObject
@end

@interface Validated : NSObject
@end


// --- GroupState ---
@interface GroupState : NSObject
@property (nonatomic, strong) NSString * Method;
@property (nonatomic, assign) BOOL IsFollowed;
@property (nonatomic, strong) NSString * GroupMenu;
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, assign) BOOL isFollowed;
@property (nonatomic, strong) NSString * groupMenu;
@property (nonatomic, strong) NSString * groupId;
@end

// --- Organization ---
@interface Organization : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * Name;
@property (nonatomic, strong) NSString * QortexURL;
@property (nonatomic, strong) NSString * Summary;
@property (nonatomic, strong) NSString * LogoURL;
@property (nonatomic, strong) NSString * Address;
@property (nonatomic, strong) NSString * Phone;
@property (nonatomic, strong) NSString * Website;
@property (nonatomic, strong) NSArray * Domains;
@property (nonatomic, assign) BOOL RestrictSubscriptionMail;
@end

// --- Blog ---
@interface Blog : NSObject
@property (nonatomic, strong) NSString * Title;
@property (nonatomic, strong) NSString * Description;
@property (nonatomic, strong) NSString * SideContent;
@end

// --- EmbedUser ---
@interface EmbedUser : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * Email;
@property (nonatomic, strong) NSString * Name;
@property (nonatomic, strong) NSString * Title;
@property (nonatomic, strong) NSString * Avatar16;
@property (nonatomic, strong) NSString * Avatar32;
@property (nonatomic, strong) NSString * JID;
@property (nonatomic, strong) NSString * Timezone;
@property (nonatomic, assign) BOOL IsSuperUser;
@property (nonatomic, assign) BOOL IsShare;
@property (nonatomic, strong) NSString * OrganizationId;
@property (nonatomic, strong) NSString * OriginalOrgId;
@property (nonatomic, strong) NSString * ProfileURL;
@end

// --- PanelStatus ---
@interface PanelStatus : NSObject
@property (nonatomic, assign) BOOL AsideGroupsCollapse;
@property (nonatomic, assign) BOOL AsideOtherGroupsCollapse;
@property (nonatomic, assign) BOOL HasToDo;
@property (nonatomic, assign) BOOL HasDraft;
@property (nonatomic, assign) BOOL HasWatchList;
@property (nonatomic, assign) BOOL HasChat;
@property (nonatomic, strong) NSNumber * ShowMarkUnreadThreshold;
@end

// --- GroupSelectorItem ---
@interface GroupSelectorItem : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * Name;
@property (nonatomic, assign) BOOL IsSelected;
@end

// --- Attachment ---
@interface Attachment : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSArray * OwnerId;
@property (nonatomic, strong) NSString * Category;
@property (nonatomic, strong) NSString * Filename;
@property (nonatomic, strong) NSString * ShortFilename;
@property (nonatomic, strong) NSString * ContentType;
@property (nonatomic, strong) NSString * ContentId;
@property (nonatomic, strong) NSString * MD5;
@property (nonatomic, strong) NSNumber * ContentLength;
@property (nonatomic, strong) NSString * Error;
@property (nonatomic, strong) NSArray * GroupId;
@property (nonatomic, strong) NSDate * UploadTime;
@property (nonatomic, strong) NSNumber * Width;
@property (nonatomic, strong) NSNumber * Height;
@property (nonatomic, strong) NSString * URL;
@property (nonatomic, strong) NSString * ImageIconURL;
@property (nonatomic, strong) NSString * FileIconURL;
@property (nonatomic, strong) NSString * HumanSize;
@property (nonatomic, assign) BOOL IsImage;
@property (nonatomic, strong) NSString * FileKind;
@end

// --- LinkedEntry ---
@interface LinkedEntry : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * EType;
@property (nonatomic, strong) NSString * Title;
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * AuthorId;
@property (nonatomic, assign) BOOL IsRoot;
@property (nonatomic, strong) NSString * RootId;
@property (nonatomic, strong) NSString * RootEntryTitle;
@property (nonatomic, strong) NSString * Link;
@end

// --- Newsletter ---
@interface Newsletter : NSObject
@property (nonatomic, strong) NSString * Email;
@end

// --- OrgSettings ---
@interface OrgSettings : NSObject
@property (nonatomic, assign) BOOL AllowUsersCreateGroups;
@property (nonatomic, assign) BOOL AllowUsersInvitePeople;
@end

// --- GroupCount ---
@interface GroupCount : NSObject
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSNumber * UnreadCount;
@end

// --- GroupHeaderItem ---
@interface GroupHeaderItem : NSObject
@property (nonatomic, assign) BOOL HasToFollow;
@property (nonatomic, assign) BOOL IsFollowing;
@property (nonatomic, assign) BOOL IsManaging;
@property (nonatomic, assign) BOOL HasFileTab;
@property (nonatomic, assign) BOOL HasToDoTab;
@property (nonatomic, assign) BOOL IsSystemMessage;
@property (nonatomic, assign) BOOL SelectedGroup;
@end

// --- InlineHelp ---
@interface InlineHelp : NSObject
@property (nonatomic, assign) BOOL WhatFeed;
@property (nonatomic, assign) BOOL WhatGroup;
@property (nonatomic, assign) BOOL WhatNext;
@property (nonatomic, assign) BOOL WhatChats;
@property (nonatomic, assign) BOOL WhatWatchList;
@property (nonatomic, assign) BOOL AboutTodos;
@property (nonatomic, assign) BOOL GettingOut;
@property (nonatomic, strong) NSString * InviteOthersURL;
@property (nonatomic, strong) NSString * WhatNextURL;
@property (nonatomic, strong) NSString * WhatChatsURL;
@end

// --- EmailChanger ---
@interface EmailChanger : NSObject
@property (nonatomic, strong) NSString * Token;
@property (nonatomic, strong) NSString * Email;
@end

// --- HelpInfo ---
@interface HelpInfo : NSObject
@property (nonatomic, strong) NSString * FirstName;
@property (nonatomic, strong) NSString * LastName;
@property (nonatomic, strong) NSString * CompanyName;
@property (nonatomic, strong) NSString * CompanySize;
@property (nonatomic, strong) NSString * Email;
@property (nonatomic, strong) NSString * Phone;
@property (nonatomic, strong) NSString * Country;
@property (nonatomic, strong) NSString * City;
@property (nonatomic, strong) NSString * HelpContent;
@end

// --- CanNotBlankError ---
@interface CanNotBlankError : NSObject
@property (nonatomic, strong) NSString * Field;
@property (nonatomic, strong) NSString * field;
@property (nonatomic, strong) CanNotBlankError * this;
@end

// --- EntryInput ---
@interface EntryInput : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * EType;
@property (nonatomic, strong) NSString * Title;
@property (nonatomic, strong) NSString * Slug;
@property (nonatomic, strong) NSString * Content;
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * IsToGroup;
@property (nonatomic, strong) NSString * ToUserIds;
@property (nonatomic, strong) NSString * MentionedUserIds;
@property (nonatomic, strong) NSString * IsPublished;
@property (nonatomic, strong) NSString * IsAcknowledgement;
@property (nonatomic, strong) NSString * TaskRequireType;
@property (nonatomic, strong) NSString * TaskDue;
@property (nonatomic, strong) NSString * RootId;
@property (nonatomic, strong) NSString * IsCommentAcknowledgement;
@property (nonatomic, strong) NSString * BaseOnEntryId;
@property (nonatomic, strong) NSString * NewVersion;
@property (nonatomic, strong) NSString * OldGroupId;
@property (nonatomic, assign) BOOL KnowledgeBase;
@property (nonatomic, assign) BOOL AnyoneCanEdit;
@property (nonatomic, assign) BOOL Presentation;
@property (nonatomic, assign) BOOL IsFromEmail;
@property (nonatomic, strong) NSString * Email;
@property (nonatomic, strong) NSString * Name;
@end

// --- BroadcastInput ---
@interface BroadcastInput : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * Title;
@property (nonatomic, strong) NSString * Content;
@property (nonatomic, strong) NSArray * ToOrgIds;
@property (nonatomic, strong) NSString * BroadcastType;
@property (nonatomic, strong) NSString * RootId;
@end

// --- GroupInput ---
@interface GroupInput : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * Name;
@property (nonatomic, strong) NSString * Description;
@property (nonatomic, strong) NSString * Type;
@property (nonatomic, strong) NSString * LogoURL;
@property (nonatomic, strong) NSString * IconName;
@property (nonatomic, strong) NSString * Slug;
@property (nonatomic, assign) BOOL IsPrivate;
@property (nonatomic, assign) BOOL IsShared;
@property (nonatomic, strong) NSArray * GroupOwners;
@property (nonatomic, strong) NSArray * InvitedOrgIds;
@property (nonatomic, strong) NSString * ActionOrgId;
@end

// --- OrgSettingsInput ---
@interface OrgSettingsInput : NSObject
@property (nonatomic, assign) BOOL AllowUsersCreateGroups;
@property (nonatomic, assign) BOOL AllowUsersInvitePeople;
@end

// --- OrganizationInput ---
@interface OrganizationInput : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * OType;
@property (nonatomic, strong) NSString * Name;
@property (nonatomic, strong) NSString * Summary;
@property (nonatomic, strong) NSString * Address;
@property (nonatomic, strong) NSString * Phone;
@property (nonatomic, strong) NSString * Website;
@property (nonatomic, strong) NSString * Domain;
@property (nonatomic, strong) NSArray * Domains;
@property (nonatomic, assign) BOOL RestrictSubscriptionMail;
@property (nonatomic, strong) NSString * AuthorId;
@property (nonatomic, strong) NSArray * MemberIds;
@property (nonatomic, strong) NSArray * GroupIds;
@property (nonatomic, strong) NSString * QortexURL;
@property (nonatomic, strong) NSString * LogoURL;
@property (nonatomic, strong) NSString * ChatToken;
@property (nonatomic, strong) NSNumber * RegistrationMode;
@end

// --- LikeInput ---
@interface LikeInput : NSObject
@property (nonatomic, strong) NSString * EntryId;
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * Like;
@end

// --- PreferencesInput ---
@interface PreferencesInput : NSObject
@property (nonatomic, strong) NSString * Timezone;
@property (nonatomic, strong) NSString * TimezoneOffset;
@property (nonatomic, strong) NSString * PreferFullName;
@property (nonatomic, strong) NSString * EnterForNewLine;
@property (nonatomic, strong) NSString * AsideGroupsCollapse;
@property (nonatomic, strong) NSString * AsideOtherGroupsCollapse;
@property (nonatomic, strong) NSString * ShowMarkUnreadThreshold;
@property (nonatomic, strong) NSString * AdminModeOn;
@property (nonatomic, strong) NSString * PreferMarkdown;
@property (nonatomic, strong) NSString * AutoFollowPublicGroup;
@end

// --- MemberAccountInput ---
@interface MemberAccountInput : NSObject
@property (nonatomic, strong) NSString * FirstName;
@property (nonatomic, strong) NSString * LastName;
@property (nonatomic, strong) NSString * AvatarURL;
@end

// --- NewsletterInput ---
@interface NewsletterInput : NSObject
@property (nonatomic, strong) NSString * Email;
@end

// --- ShareChatInput ---
@interface ShareChatInput : NSObject
@property (nonatomic, strong) NSString * Title;
@property (nonatomic, strong) NSString * Content;
@property (nonatomic, strong) NSString * BasedConvId;
@property (nonatomic, strong) NSString * BaseOnEntryId;
@property (nonatomic, strong) NSString * GroupId;
@end

// --- HelpInput ---
@interface HelpInput : NSObject
@property (nonatomic, strong) NSString * FirstName;
@property (nonatomic, strong) NSString * LastName;
@property (nonatomic, strong) NSString * CompanyName;
@property (nonatomic, strong) NSString * CompanySize;
@property (nonatomic, strong) NSString * Email;
@property (nonatomic, strong) NSString * Phone;
@property (nonatomic, strong) NSString * Country;
@property (nonatomic, strong) NSString * City;
@property (nonatomic, strong) NSString * HelpContent;
@end

// --- UserProfileInput ---
@interface UserProfileInput : NSObject
@property (nonatomic, strong) NSString * Summary;
@property (nonatomic, strong) NSString * Title;
@property (nonatomic, strong) NSString * Department;
@property (nonatomic, strong) NSString * Location;
@property (nonatomic, strong) NSString * Expertise;
@property (nonatomic, strong) NSString * Interests;
@property (nonatomic, strong) NSString * BirthMonth;
@property (nonatomic, strong) NSString * BirthDay;
@property (nonatomic, strong) NSString * WorkPhone;
@property (nonatomic, strong) NSString * Mobile;
@property (nonatomic, strong) NSString * Twitter;
@property (nonatomic, strong) NSString * Skype;
@property (nonatomic, strong) NSString * Facebook;
@property (nonatomic, strong) NSArray * OtherWebsites;
@end

// --- DraftReply ---
@interface DraftReply : NSObject
@property (nonatomic, strong) NSString * Method;
@property (nonatomic, assign) BOOL Success;
@property (nonatomic, assign) BOOL IsManual;
@property (nonatomic, strong) NSString * Message;
@end

// --- Preferences ---
@interface Preferences : NSObject
@property (nonatomic, strong) NSString * Timezone;
@property (nonatomic, strong) NSString * TimezoneOffset;
@property (nonatomic, assign) BOOL PreferFullName;
@property (nonatomic, assign) BOOL EnterForNewLine;
@property (nonatomic, assign) BOOL AsideGroupsCollapse;
@property (nonatomic, assign) BOOL AsideOtherGroupsCollapse;
@property (nonatomic, strong) NSNumber * ShowMarkUnreadThreshold;
@property (nonatomic, assign) BOOL AdminModeOn;
@property (nonatomic, assign) BOOL PreferMarkdown;
@property (nonatomic, assign) BOOL AutoFollowPublicGroup;
@end

// --- EmbedOrg ---
@interface EmbedOrg : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * Name;
@property (nonatomic, strong) NSString * LogoURL;
@property (nonatomic, assign) BOOL NoNeedToShare;
@end

// --- BlogEntry ---
@interface BlogEntry : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * Title;
@property (nonatomic, strong) NSString * Slug;
@property (nonatomic, strong) NSDate * CreatedAt;
@property (nonatomic, strong) NSDate * UpdatedAt;
@property (nonatomic, strong) NSString * Permalink;
@property (nonatomic, strong) NSString * CreateCommentURL;
@property (nonatomic, strong) NSString * HtmlContent;
@property (nonatomic, strong) EmbedUser * Author;
@property (nonatomic, strong) NSArray * Comments;
@end

// --- GroupUsers ---
@interface GroupUsers : NSObject
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSArray * EmbedUsers;
@end

// --- MyCount ---
@interface MyCount : NSObject
@property (nonatomic, strong) NSString * UserId;
@property (nonatomic, strong) NSNumber * FollowedUnreadCount;
@property (nonatomic, strong) NSNumber * NotificationUnreadCount;
@property (nonatomic, strong) NSNumber * ActiveTasksCount;
@property (nonatomic, strong) NSArray * GroupCounts;
@end

// --- AvailableUser ---
@interface AvailableUser : NSObject
@property (nonatomic, strong) NSString * Method;
@property (nonatomic, strong) EmbedUser * TheUser;
@property (nonatomic, strong) EmbedUser * embedUser;
@end

// --- Group ---
@interface Group : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * Name;
@property (nonatomic, strong) NSString * Description;
@property (nonatomic, strong) NSString * GType;
@property (nonatomic, strong) NSString * LogoURL;
@property (nonatomic, strong) NSString * IconName;
@property (nonatomic, strong) NSString * Link;
@property (nonatomic, strong) NSString * Slug;
@property (nonatomic, strong) EmbedUser * Author;
@property (nonatomic, assign) BOOL IsAdmin;
@property (nonatomic, assign) BOOL IsPrivate;
@property (nonatomic, assign) BOOL Editable;
@property (nonatomic, assign) BOOL Managable;
@property (nonatomic, assign) BOOL FollowedByMe;
@property (nonatomic, assign) BOOL AdministratedByMe;
@property (nonatomic, assign) BOOL IsShared;
@property (nonatomic, assign) BOOL IsDefaultLogoURL;
@property (nonatomic, strong) NSString * HostOrgName;
@property (nonatomic, assign) BOOL IsDispayHostOrgName;
@property (nonatomic, strong) NSNumber * EntriesCount;
@property (nonatomic, strong) NSNumber * FollowersCount;
@property (nonatomic, assign) BOOL IsAnnoucement;
@property (nonatomic, strong) NSArray * GroupOwners;
@end

// --- GroupSelector ---
@interface GroupSelector : NSObject
@property (nonatomic, strong) NSString * Header;
@property (nonatomic, strong) NSString * SelectedGroupId;
@property (nonatomic, strong) GroupSelectorItem * SysMessage;
@property (nonatomic, strong) NSArray * FollowingGroups;
@property (nonatomic, strong) NSArray * UnFollowingGroups;
@end

// --- Task ---
@interface Task : NSObject
@property (nonatomic, assign) BOOL IsTaskOwner;
@property (nonatomic, assign) BOOL IsTaskAssignee;
@property (nonatomic, assign) BOOL IsOthers;
@property (nonatomic, assign) BOOL IsCurrentUserDone;
@property (nonatomic, assign) BOOL IsAcknowledgement;
@property (nonatomic, assign) BOOL IsTodoForOne;
@property (nonatomic, assign) BOOL IsTodoForAll;
@property (nonatomic, assign) BOOL IsCompleted;
@property (nonatomic, assign) BOOL IsClosed;
@property (nonatomic, assign) BOOL IsDueToday;
@property (nonatomic, assign) BOOL IsOverDue;
@property (nonatomic, strong) NSDate * CreatedAt;
@property (nonatomic, strong) NSDate * Due;
@property (nonatomic, strong) NSDate * CompletedAt;
@property (nonatomic, strong) NSString * LocalCreatedDate;
@property (nonatomic, strong) NSString * LocalDue;
@property (nonatomic, strong) NSString * LocalDueShortDate;
@property (nonatomic, strong) NSString * DueInputValue;
@property (nonatomic, strong) NSNumber * TotalUsersCount;
@property (nonatomic, strong) NSNumber * CompletedUsersCount;
@property (nonatomic, strong) NSNumber * PendingUsersCount;
@property (nonatomic, strong) EmbedUser * Owner;
@property (nonatomic, strong) NSArray * ToUsers;
@property (nonatomic, strong) NSArray * PendingUsers;
@property (nonatomic, strong) NSArray * CompletedUsers;
@property (nonatomic, strong) NSString * ColorCssClass;
@property (nonatomic, strong) NSString * TaskBarHtml;
@end

// --- EntryVersion ---
@interface EntryVersion : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSDate * UpdatedAt;
@property (nonatomic, strong) NSString * LocalUpdatedAt;
@property (nonatomic, strong) NSString * UpdatedAtUnixNano;
@property (nonatomic, strong) EmbedUser * CurrentVersionEditor;
@property (nonatomic, assign) BOOL IsNewVersion;
@end

// --- Message ---
@interface Message : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * ConversationId;
@property (nonatomic, strong) NSString * UserId;
@property (nonatomic, strong) NSString * Content;
@property (nonatomic, strong) NSString * HtmlContent;
@property (nonatomic, strong) NSDate * CreatedAt;
@property (nonatomic, strong) EmbedUser * EmbedUser;
@property (nonatomic, assign) BOOL ShowUser;
@property (nonatomic, strong) NSString * HighlightedContent;
@end

// --- Invitation ---
@interface Invitation : NSObject
@property (nonatomic, strong) NSString * Email;
@property (nonatomic, strong) NSString * Token;
@property (nonatomic, strong) NSString * SentAgo;
@property (nonatomic, strong) EmbedUser * ByUser;
@end

// --- EmbedEntry ---
@interface EmbedEntry : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * Title;
@property (nonatomic, strong) NSString * HtmlTitle;
@property (nonatomic, strong) NSString * EType;
@property (nonatomic, strong) EmbedUser * Author;
@property (nonatomic, strong) NSArray * ToUsers;
@property (nonatomic, strong) NSString * Link;
@end

// --- AbandonUserInfo ---
@interface AbandonUserInfo : NSObject
@property (nonatomic, strong) EmbedOrg * CurrentDisabledFromOrg;
@property (nonatomic, strong) EmbedOrg * CurrentDeletedFromOrg;
@property (nonatomic, strong) NSArray * AvailableOrgs;
@property (nonatomic, strong) NSArray * DisabledFromOrgs;
@property (nonatomic, strong) NSArray * DeletedFromOrgs;
@end

// --- Conversation ---
@interface Conversation : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * Title;
@property (nonatomic, strong) NSArray * UserIds;
@property (nonatomic, strong) NSArray * Participants;
@property (nonatomic, strong) NSDate * CreatedAt;
@property (nonatomic, strong) NSDate * EndedAt;
@property (nonatomic, strong) NSString * LocalHumanCreatedAt;
@property (nonatomic, strong) NSString * Topic;
@property (nonatomic, assign) BOOL Private;
@property (nonatomic, assign) BOOL IsClose;
@property (nonatomic, assign) BOOL IsShared;
@property (nonatomic, strong) NSArray * SharedMessageIds;
@property (nonatomic, strong) NSNumber * MessagesCount;
@property (nonatomic, strong) NSArray * Messages;
@end

// --- NotificationItem ---
@interface NotificationItem : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) EmbedUser * ToUser;
@property (nonatomic, strong) EmbedEntry * ForEntry;
@property (nonatomic, strong) EmbedUser * FromUser;
@property (nonatomic, strong) EmbedOrg * FromOrg;
@property (nonatomic, strong) EmbedEntry * CausedByEntry;
@property (nonatomic, strong) NSDate * NotifiedAt;
@property (nonatomic, strong) NSDate * ReadAt;
@property (nonatomic, assign) BOOL Readed;
@property (nonatomic, strong) NSString * Type;
@property (nonatomic, strong) NSString * Link;
@property (nonatomic, strong) NSString * SharingRequestToEmail;
@end

// --- CountNotification ---
@interface CountNotification : NSObject
@property (nonatomic, strong) NSString * Method;
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, assign) BOOL NewEntry;
@property (nonatomic, strong) NSString * EntryId;
@property (nonatomic, strong) NSString * DelType;
@property (nonatomic, strong) MyCount * MyCount;
@property (nonatomic, strong) NSNumber * NewMessageNumber;
@end

// --- SharingInvitationItem ---
@interface SharingInvitationItem : NSObject
@property (nonatomic, strong) EmbedOrg * FromOrg;
@property (nonatomic, strong) NSString * FromUserId;
@property (nonatomic, strong) Group * SharedGroup;
@property (nonatomic, assign) BOOL IsNewAccount;
@property (nonatomic, strong) NSString * Email;
@property (nonatomic, strong) NSString * Token;
@property (nonatomic, strong) NSArray * JoinedOrgs;
@property (nonatomic, assign) BOOL IsAccepted;
@property (nonatomic, assign) BOOL IsRejected;
@property (nonatomic, assign) BOOL IsPending;
@property (nonatomic, assign) BOOL IsForwarded;
@property (nonatomic, assign) BOOL IsCanceled;
@property (nonatomic, assign) BOOL IsStopped;
@property (nonatomic, strong) NSString * PendingDuration;
@property (nonatomic, strong) NSString * ToOrgName;
@property (nonatomic, strong) NSString * ToOrgId;
@end

// --- User ---
@interface User : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * Email;
@property (nonatomic, strong) NSString * Firstame;
@property (nonatomic, strong) NSString * LastName;
@property (nonatomic, strong) NSString * Name;
@property (nonatomic, strong) NSString * Title;
@property (nonatomic, strong) NSString * Avatar;
@property (nonatomic, strong) NSString * JID;
@property (nonatomic, strong) NSString * Timezone;
@property (nonatomic, assign) BOOL IsSuperUser;
@property (nonatomic, assign) BOOL IsSharedUser;
@property (nonatomic, strong) NSString * OrgId;
@property (nonatomic, strong) NSString * OriginalOrgId;
@property (nonatomic, strong) NSString * PrefixURL;
@property (nonatomic, strong) NSString * ProfileURL;
@property (nonatomic, assign) BOOL IsLoggedInUser;
@property (nonatomic, assign) BOOL IsAvailable;
@property (nonatomic, assign) BOOL IsDisabled;
@property (nonatomic, assign) BOOL IsDeleted;
@property (nonatomic, assign) BOOL FromSharedGroup;
@property (nonatomic, strong) NSString * FromOrganizationName;
@property (nonatomic, assign) BOOL Editable;
@property (nonatomic, assign) BOOL Followable;
@property (nonatomic, assign) BOOL FollowedByMe;
@property (nonatomic, assign) BOOL FollowingTheGroup;
@property (nonatomic, strong) NSString * Department;
@property (nonatomic, strong) NSString * Location;
@property (nonatomic, strong) NSArray * FollowingGroups;
@property (nonatomic, strong) Preferences * Preferences;
@end

// --- Request ---
@interface Request : NSObject
@property (nonatomic, strong) NSString * CurrentPrefixURL;
@property (nonatomic, strong) NSString * Info;
@property (nonatomic, strong) NSString * ActionButton;
@property (nonatomic, strong) EmbedOrg * FromOrg;
@property (nonatomic, strong) EmbedOrg * ToOrg;
@property (nonatomic, strong) Group * SharedGroup;
@property (nonatomic, strong) NSString * SharedOrgIdHex;
@property (nonatomic, strong) NSString * FromUserIdHex;
@property (nonatomic, strong) EmbedUser * SharedInvitee;
@property (nonatomic, strong) EmbedUser * SharedInviter;
@property (nonatomic, strong) EmbedUser * SharedResponsor;
@property (nonatomic, strong) NSString * ToEmail;
@property (nonatomic, strong) NSString * State;
@end

// --- TaskState ---
@interface TaskState : NSObject
@property (nonatomic, strong) NSString * Method;
@property (nonatomic, strong) NSString * TaskBar;
@property (nonatomic, strong) NSString * EntryId;
@property (nonatomic, strong) MyCount * MyCount;
@end

// --- Entry ---
@interface Entry : NSObject
@property (nonatomic, strong) NSString * Id;
@property (nonatomic, strong) NSString * EType;
@property (nonatomic, strong) NSString * Title;
@property (nonatomic, strong) NSString * Slug;
@property (nonatomic, strong) NSString * Content;
@property (nonatomic, strong) NSString * TypeTitle;
@property (nonatomic, strong) NSString * RootId;
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * AuthorId;
@property (nonatomic, strong) NSDate * CreatedAt;
@property (nonatomic, strong) NSDate * UpdatedAt;
@property (nonatomic, strong) NSDate * BumpedUpAt;
@property (nonatomic, strong) NSString * AllAttachmentsURL;
@property (nonatomic, strong) NSString * Permalink;
@property (nonatomic, strong) NSString * IconName;
@property (nonatomic, strong) NSString * LocalHumanCreatedAt;
@property (nonatomic, strong) NSString * LocalHumanUpdatedAt;
@property (nonatomic, strong) NSString * WholeLastUpdateAtAgo;
@property (nonatomic, strong) NSString * LastUpdateAtAgo;
@property (nonatomic, strong) NSString * MentionedUserIds;
@property (nonatomic, strong) NSString * DomainURL;
@property (nonatomic, strong) NSString * UpdatedAtUnixNano;
@property (nonatomic, strong) NSString * HtmlTitle;
@property (nonatomic, strong) NSString * HtmlContent;
@property (nonatomic, strong) NSString * HtmlContentPart;
@property (nonatomic, strong) NSString * TaskHtmlContentPart;
@property (nonatomic, strong) NSString * WatchlistHtml;
@property (nonatomic, strong) NSString * ToUsersHtml;
@property (nonatomic, strong) NSString * LikedByUsersHtml;
@property (nonatomic, strong) NSString * NotifyOptionsHtml;
@property (nonatomic, strong) NSString * Link;
@property (nonatomic, strong) NSString * UploadURL;
@property (nonatomic, assign) BOOL IsShared;
@property (nonatomic, assign) BOOL IsPublished;
@property (nonatomic, assign) BOOL IsCanPublish;
@property (nonatomic, assign) BOOL IsSystemMessage;
@property (nonatomic, strong) NSString * SystemMessageType;
@property (nonatomic, strong) NSString * BroadcastType;
@property (nonatomic, assign) BOOL IsBroadcast;
@property (nonatomic, assign) BOOL IsBroadcastTypeToAllAdmins;
@property (nonatomic, assign) BOOL IsBroadcastTypeToAllUsers;
@property (nonatomic, assign) BOOL IsBroadcastTypeToSomeOrgs;
@property (nonatomic, assign) BOOL IsFromSuperOrg;
@property (nonatomic, assign) BOOL IsFeedback;
@property (nonatomic, strong) EmbedOrg * FromOrg;
@property (nonatomic, strong) NSArray * ToOrgs;
@property (nonatomic, strong) NSString * ToOrgsHtml;
@property (nonatomic, assign) BOOL IsRequest;
@property (nonatomic, strong) Request * Request;
@property (nonatomic, assign) BOOL VisibleForSuperUserInSuperOrg;
@property (nonatomic, assign) BOOL VisibleForSuperOrg;
@property (nonatomic, assign) BOOL IsKnowledgeBase;
@property (nonatomic, assign) BOOL IsPost;
@property (nonatomic, assign) BOOL IsComment;
@property (nonatomic, assign) BOOL IsTask;
@property (nonatomic, assign) BOOL IsChat;
@property (nonatomic, assign) BOOL IsTaskToDo;
@property (nonatomic, assign) BOOL IsTaskAck;
@property (nonatomic, assign) BOOL IsInWatchList;
@property (nonatomic, strong) NSString * IsToGroup;
@property (nonatomic, assign) BOOL CurrentUserCanEdit;
@property (nonatomic, assign) BOOL CanEdit;
@property (nonatomic, assign) BOOL CanReply;
@property (nonatomic, assign) BOOL ManagerCanEdit;
@property (nonatomic, assign) BOOL LikedByMe;
@property (nonatomic, assign) BOOL HasInlineTask;
@property (nonatomic, assign) BOOL TaskIsCompleted;
@property (nonatomic, assign) BOOL IsRoot;
@property (nonatomic, assign) BOOL IsUnread;
@property (nonatomic, assign) BOOL IsUpdated;
@property (nonatomic, assign) BOOL IsLastVersion;
@property (nonatomic, assign) BOOL Presentation;
@property (nonatomic, assign) BOOL AnyoneCanEdit;
@property (nonatomic, assign) BOOL IsInGroup;
@property (nonatomic, assign) BOOL IsFromEmail;
@property (nonatomic, strong) NSNumber * AllAttachmentsCount;
@property (nonatomic, strong) NSNumber * CommentsCount;
@property (nonatomic, strong) NSNumber * AllLikesCount;
@property (nonatomic, strong) NSNumber * VersionCount;
@property (nonatomic, strong) EmbedUser * Author;
@property (nonatomic, strong) EmbedUser * CurrentVersionEditor;
@property (nonatomic, strong) Group * Group;
@property (nonatomic, strong) Task * Task;
@property (nonatomic, strong) Conversation * Conversation;
@property (nonatomic, strong) NSArray * LinkedEntries;
@property (nonatomic, strong) NSArray * Versions;
@property (nonatomic, strong) NSArray * ToUsers;
@property (nonatomic, strong) NSArray * MentionedUsers;
@property (nonatomic, strong) NSArray * LikedByUsers;
@property (nonatomic, strong) NSArray * Attachments;
@property (nonatomic, strong) Attachment * FirstPicture;
@property (nonatomic, strong) NSArray * Comments;
@property (nonatomic, strong) NSArray * ExternalComments;
@property (nonatomic, strong) NSArray * CurrentVersionComments;
@property (nonatomic, strong) NSArray * OtherVersionsComments;
@property (nonatomic, strong) Entry * NewComment;
@property (nonatomic, strong) Entry * NewEntry;
@property (nonatomic, strong) GroupSelector * GroupSlector;
@end

// --- MyNotifications ---
@interface MyNotifications : NSObject
@property (nonatomic, strong) NSArray * NotificationItems;
@property (nonatomic, assign) BOOL HasMore;
@property (nonatomic, strong) NSNumber * LatestNotifyTime;
@end

// --- MyChats ---
@interface MyChats : NSObject
@property (nonatomic, strong) NSArray * ChatEntries;
@property (nonatomic, assign) BOOL HasMore;
@property (nonatomic, strong) NSNumber * LatestCreateTime;
@property (nonatomic, assign) BOOL WhatChats;
@property (nonatomic, strong) NSString * PrefixURL;
@end

// --- WatchItem ---
@interface WatchItem : NSObject
@property (nonatomic, strong) NSNumber * AttachCnt;
@property (nonatomic, strong) NSNumber * CommentCnt;
@property (nonatomic, strong) NSNumber * LikeCnt;
@property (nonatomic, strong) NSString * AttachCntStr;
@property (nonatomic, strong) NSString * CommentCntStr;
@property (nonatomic, strong) NSString * LikeCntStr;
@property (nonatomic, strong) NSDate * WatchTime;
@property (nonatomic, strong) Entry * WatchEntry;
@end

// --- MyTask ---
@interface MyTask : NSObject
@property (nonatomic, strong) NSArray * TasksForMe;
@property (nonatomic, strong) NSArray * MyCreatedTasks;
@property (nonatomic, assign) BOOL AboutTodos;
@end

// --- DraftList ---
@interface DraftList : NSObject
@property (nonatomic, strong) NSArray * DraftItems;
@end

// --- WatchList ---
@interface WatchList : NSObject
@property (nonatomic, strong) NSArray * Items;
@property (nonatomic, assign) BOOL WhatWatchList;
@end


// === Interfaces ===


// --- CancelChangingEmailParams ---
@interface NoAuthUserServiceCancelChangingEmailParams : NSObject
@property (nonatomic, strong) NSString * Token;
@end

// --- CancelChangingEmailResults ---
@interface NoAuthUserServiceCancelChangingEmailResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- ChangeEmailParams ---
@interface NoAuthUserServiceChangeEmailParams : NSObject
@property (nonatomic, strong) NSString * Token;
@end

// --- ChangeEmailResults ---
@interface NoAuthUserServiceChangeEmailResults : NSObject
@property (nonatomic, strong) NSString * ActivationToken;
@property (nonatomic, strong) NSError * Err;
@end

// --- PrepareChangeEmailParams ---
@interface NoAuthUserServicePrepareChangeEmailParams : NSObject
@property (nonatomic, strong) NSString * MemberId;
@property (nonatomic, strong) NSString * NewEmail;
@end

// --- PrepareChangeEmailResults ---
@interface NoAuthUserServicePrepareChangeEmailResults : NSObject
@property (nonatomic, strong) EmailChanger * R;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- GetSharingInviationParams ---
@interface NoAuthUserServiceGetSharingInviationParams : NSObject
@property (nonatomic, strong) NSString * SharingInviationToken;
@property (nonatomic, strong) NSString * MemberId;
@end

// --- GetSharingInviationResults ---
@interface NoAuthUserServiceGetSharingInviationResults : NSObject
@property (nonatomic, strong) SharingInvitationItem * R;
@property (nonatomic, strong) NSError * Err;
@end

// --- ChangeEmailToAcceptSharingParams ---
@interface NoAuthUserServiceChangeEmailToAcceptSharingParams : NSObject
@property (nonatomic, strong) NSString * Token;
@property (nonatomic, strong) NSString * NewEmail;
@end

// --- ChangeEmailToAcceptSharingResults ---
@interface NoAuthUserServiceChangeEmailToAcceptSharingResults : NSObject
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- AskHelpParams ---
@interface NoAuthUserServiceAskHelpParams : NSObject
@property (nonatomic, strong) HelpInput * Input;
@end

// --- AskHelpResults ---
@interface NoAuthUserServiceAskHelpResults : NSObject
@property (nonatomic, strong) HelpInfo * Help;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- BlogEntriesParams ---
@interface NoAuthUserServiceBlogEntriesParams : NSObject
@property (nonatomic, strong) NSString * Doi;
@property (nonatomic, strong) NSNumber * PageNum;
@property (nonatomic, strong) NSNumber * Limit;
@end

// --- BlogEntriesResults ---
@interface NoAuthUserServiceBlogEntriesResults : NSObject
@property (nonatomic, strong) Blog * Blog;
@property (nonatomic, strong) NSArray * R;
@property (nonatomic, strong) NSNumber * TotalPageNum;
@property (nonatomic, strong) NSError * Err;
@end

// --- BlogEntryBySlugParams ---
@interface NoAuthUserServiceBlogEntryBySlugParams : NSObject
@property (nonatomic, strong) NSString * Doi;
@property (nonatomic, strong) NSString * Slug;
@end

// --- BlogEntryBySlugResults ---
@interface NoAuthUserServiceBlogEntryBySlugResults : NSObject
@property (nonatomic, strong) Blog * Blog;
@property (nonatomic, strong) BlogEntry * R;
@property (nonatomic, strong) NSError * Err;
@end

// --- CreateExternalCommentParams ---
@interface NoAuthUserServiceCreateExternalCommentParams : NSObject
@property (nonatomic, strong) NSString * Doi;
@property (nonatomic, strong) EntryInput * Input;
@end

// --- CreateExternalCommentResults ---
@interface NoAuthUserServiceCreateExternalCommentResults : NSObject
@property (nonatomic, strong) BlogEntry * R;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- CheckSlugParams ---
@interface NoAuthUserServiceCheckSlugParams : NSObject
@property (nonatomic, strong) NSString * Doi;
@property (nonatomic, strong) NSString * Slug;
@end

// --- CheckSlugResults ---
@interface NoAuthUserServiceCheckSlugResults : NSObject
@property (nonatomic, strong) NSString * ValidSlug;
@property (nonatomic, strong) NSError * Err;
@end

// --- CreateNewsletterParams ---
@interface NoAuthUserServiceCreateNewsletterParams : NSObject
@property (nonatomic, strong) NewsletterInput * Input;
@end

// --- CreateNewsletterResults ---
@interface NoAuthUserServiceCreateNewsletterResults : NSObject
@property (nonatomic, strong) Newsletter * R;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end


@interface NoAuthUserService : NSObject

- (NoAuthUserServiceCancelChangingEmailResults *) CancelChangingEmail:(NSString *)token;

- (NoAuthUserServiceChangeEmailResults *) ChangeEmail:(NSString *)token;

- (NoAuthUserServicePrepareChangeEmailResults *) PrepareChangeEmail:(NSString *)memberId newEmail:(NSString *)newEmail;

- (NoAuthUserServiceGetSharingInviationResults *) GetSharingInviation:(NSString *)sharingInviationToken memberId:(NSString *)memberId;

- (NoAuthUserServiceChangeEmailToAcceptSharingResults *) ChangeEmailToAcceptSharing:(NSString *)token newEmail:(NSString *)newEmail;

- (NoAuthUserServiceAskHelpResults *) AskHelp:(HelpInput *)input;

- (NoAuthUserServiceBlogEntriesResults *) BlogEntries:(NSString *)doi pageNum:(NSNumber *)pageNum limit:(NSNumber *)limit;

- (NoAuthUserServiceBlogEntryBySlugResults *) BlogEntryBySlug:(NSString *)doi slug:(NSString *)slug;

- (NoAuthUserServiceCreateExternalCommentResults *) CreateExternalComment:(NSString *)doi input:(EntryInput *)input;

- (NoAuthUserServiceCheckSlugResults *) CheckSlug:(NSString *)doi slug:(NSString *)slug;

- (NoAuthUserServiceCreateNewsletterResults *) CreateNewsletter:(NewsletterInput *)input;
@end


// --- GetAbandonUserInfoParams ---
@interface AuthMemberServiceGetAbandonUserInfoParams : NSObject
@property (nonatomic, strong) NSString * OrganizationId;
@property (nonatomic, strong) NSString * MemberId;
@end

// --- GetAbandonUserInfoResults ---
@interface AuthMemberServiceGetAbandonUserInfoResults : NSObject
@property (nonatomic, strong) AbandonUserInfo * Info;
@property (nonatomic, strong) NSError * Err;
@end

// --- SwitchOrganizationParams ---
@interface AuthMemberServiceSwitchOrganizationParams : NSObject
@property (nonatomic, strong) NSString * OrgId;
@end

// --- SwitchOrganizationResults ---
@interface AuthMemberServiceSwitchOrganizationResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- GetSharingInviationByTokenParams ---
@interface AuthMemberServiceGetSharingInviationByTokenParams : NSObject
@property (nonatomic, strong) NSString * SharingInviationToken;
@end

// --- GetSharingInviationByTokenResults ---
@interface AuthMemberServiceGetSharingInviationByTokenResults : NSObject
@property (nonatomic, strong) SharingInvitationItem * R;
@property (nonatomic, strong) NSError * Err;
@end

// --- RejectSharingBeforeForwardingParams ---
@interface AuthMemberServiceRejectSharingBeforeForwardingParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * Email;
@end

// --- RejectSharingBeforeForwardingResults ---
@interface AuthMemberServiceRejectSharingBeforeForwardingResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- ResponseSharingRequestParams ---
@interface AuthMemberServiceResponseSharingRequestParams : NSObject
@property (nonatomic, strong) NSString * Token;
@property (nonatomic, strong) NSString * FromOrgId;
@property (nonatomic, strong) NSString * FromUserId;
@property (nonatomic, strong) NSString * ForSharingOrgId;
@property (nonatomic, strong) NSString * GroupId;
@end

// --- ResponseSharingRequestResults ---
@interface AuthMemberServiceResponseSharingRequestResults : NSObject
@property (nonatomic, strong) NSString * PrefixURL;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end


@interface AuthMemberService : NSObject

- (AuthMemberServiceGetAbandonUserInfoResults *) GetAbandonUserInfo:(NSString *)organizationId memberId:(NSString *)memberId;

- (AuthMemberServiceSwitchOrganizationResults *) SwitchOrganization:(NSString *)orgId;

- (AuthMemberServiceGetSharingInviationByTokenResults *) GetSharingInviationByToken:(NSString *)sharingInviationToken;

- (AuthMemberServiceRejectSharingBeforeForwardingResults *) RejectSharingBeforeForwarding:(NSString *)groupId email:(NSString *)email;

- (AuthMemberServiceResponseSharingRequestResults *) ResponseSharingRequest:(NSString *)token fromOrgId:(NSString *)fromOrgId fromUserId:(NSString *)fromUserId forSharingOrgId:(NSString *)forSharingOrgId groupId:(NSString *)groupId;
@end


// --- NewEntryParams ---
@interface AuthUserServiceNewEntryParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@end

// --- NewEntryResults ---
@interface AuthUserServiceNewEntryResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) NSError * Err;
@end

// --- QortexMessagesParams ---
@interface AuthUserServiceQortexMessagesParams : NSObject
@property (nonatomic, strong) NSString * MesssageType;
@property (nonatomic, strong) NSString * Before;
@property (nonatomic, strong) NSNumber * Limit;
@end

// --- QortexMessagesResults ---
@interface AuthUserServiceQortexMessagesResults : NSObject
@property (nonatomic, strong) NSArray * Entries;
@property (nonatomic, strong) NSError * Err;
@end

// --- CreateBroadcastParams ---
@interface AuthUserServiceCreateBroadcastParams : NSObject
@property (nonatomic, strong) BroadcastInput * Input;
@end

// --- CreateBroadcastResults ---
@interface AuthUserServiceCreateBroadcastResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- CreateBroadcastCommentParams ---
@interface AuthUserServiceCreateBroadcastCommentParams : NSObject
@property (nonatomic, strong) BroadcastInput * Input;
@end

// --- CreateBroadcastCommentResults ---
@interface AuthUserServiceCreateBroadcastCommentResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- GetRequestParams ---
@interface AuthUserServiceGetRequestParams : NSObject
@property (nonatomic, strong) NSString * EntryId;
@end

// --- GetRequestResults ---
@interface AuthUserServiceGetRequestResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) NSError * Err;
@end

// --- EditBroadcastParams ---
@interface AuthUserServiceEditBroadcastParams : NSObject
@property (nonatomic, strong) NSString * EntryId;
@end

// --- EditBroadcastResults ---
@interface AuthUserServiceEditBroadcastResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) NSError * Err;
@end

// --- EditBroadcastCommentParams ---
@interface AuthUserServiceEditBroadcastCommentParams : NSObject
@property (nonatomic, strong) NSString * EntryId;
@end

// --- EditBroadcastCommentResults ---
@interface AuthUserServiceEditBroadcastCommentResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) NSError * Err;
@end

// --- UpdateBroadcastParams ---
@interface AuthUserServiceUpdateBroadcastParams : NSObject
@property (nonatomic, strong) BroadcastInput * Input;
@end

// --- UpdateBroadcastResults ---
@interface AuthUserServiceUpdateBroadcastResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- UpdateBroadcastCommentParams ---
@interface AuthUserServiceUpdateBroadcastCommentParams : NSObject
@property (nonatomic, strong) BroadcastInput * Input;
@end

// --- UpdateBroadcastCommentResults ---
@interface AuthUserServiceUpdateBroadcastCommentResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- CreatePostParams ---
@interface AuthUserServiceCreatePostParams : NSObject
@property (nonatomic, strong) EntryInput * Input;
@end

// --- CreatePostResults ---
@interface AuthUserServiceCreatePostResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- CreateTaskParams ---
@interface AuthUserServiceCreateTaskParams : NSObject
@property (nonatomic, strong) EntryInput * Input;
@end

// --- CreateTaskResults ---
@interface AuthUserServiceCreateTaskResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- CloseTaskParams ---
@interface AuthUserServiceCloseTaskParams : NSObject
@property (nonatomic, strong) NSString * EntryId;
@property (nonatomic, strong) NSString * GroupId;
@end

// --- CloseTaskResults ---
@interface AuthUserServiceCloseTaskResults : NSObject
@property (nonatomic, strong) Task * Entry;
@property (nonatomic, strong) NSError * Err;
@end

// --- CreateCommentParams ---
@interface AuthUserServiceCreateCommentParams : NSObject
@property (nonatomic, strong) EntryInput * Input;
@end

// --- CreateCommentResults ---
@interface AuthUserServiceCreateCommentResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- GetCommentParams ---
@interface AuthUserServiceGetCommentParams : NSObject
@property (nonatomic, strong) NSString * EntryId;
@property (nonatomic, strong) NSString * GroupId;
@end

// --- GetCommentResults ---
@interface AuthUserServiceGetCommentResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) NSError * Err;
@end

// --- UpdateCommentParams ---
@interface AuthUserServiceUpdateCommentParams : NSObject
@property (nonatomic, strong) EntryInput * Input;
@end

// --- UpdateCommentResults ---
@interface AuthUserServiceUpdateCommentResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- UpdateEntryParams ---
@interface AuthUserServiceUpdateEntryParams : NSObject
@property (nonatomic, strong) EntryInput * Input;
@end

// --- UpdateEntryResults ---
@interface AuthUserServiceUpdateEntryResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- GetLatestUpdatedEntryIdByTitleParams ---
@interface AuthUserServiceGetLatestUpdatedEntryIdByTitleParams : NSObject
@property (nonatomic, strong) NSString * Title;
@property (nonatomic, strong) NSString * GroupId;
@end

// --- GetLatestUpdatedEntryIdByTitleResults ---
@interface AuthUserServiceGetLatestUpdatedEntryIdByTitleResults : NSObject
@property (nonatomic, strong) NSString * R;
@property (nonatomic, strong) NSError * Err;
@end

// --- GetEntryParams ---
@interface AuthUserServiceGetEntryParams : NSObject
@property (nonatomic, strong) NSString * EntryId;
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * UpdateAtUnixNano;
@property (nonatomic, strong) NSString * SearchKeyWords;
@end

// --- GetEntryResults ---
@interface AuthUserServiceGetEntryResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) NSError * Err;
@end

// --- DeleteEntryParams ---
@interface AuthUserServiceDeleteEntryParams : NSObject
@property (nonatomic, strong) NSString * EntryId;
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * DType;
@end

// --- DeleteEntryResults ---
@interface AuthUserServiceDeleteEntryResults : NSObject
@property (nonatomic, strong) NSString * DelType;
@property (nonatomic, strong) NSError * Err;
@end

// --- EntryAttachmentsParams ---
@interface AuthUserServiceEntryAttachmentsParams : NSObject
@property (nonatomic, strong) NSString * EntryId;
@property (nonatomic, strong) NSString * GroupId;
@end

// --- EntryAttachmentsResults ---
@interface AuthUserServiceEntryAttachmentsResults : NSObject
@property (nonatomic, strong) NSArray * Attachments;
@property (nonatomic, strong) NSError * Err;
@end

// --- OtherCommentsParams ---
@interface AuthUserServiceOtherCommentsParams : NSObject
@property (nonatomic, strong) NSString * EntryId;
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * VersionUpdateat;
@property (nonatomic, strong) NSString * SearchKeyWords;
@end

// --- OtherCommentsResults ---
@interface AuthUserServiceOtherCommentsResults : NSObject
@property (nonatomic, strong) NSArray * Comments;
@property (nonatomic, strong) NSError * Err;
@end

// --- GroupEntriesParams ---
@interface AuthUserServiceGroupEntriesParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * EntryType;
@property (nonatomic, strong) NSString * Before;
@property (nonatomic, strong) NSNumber * Limit;
@end

// --- GroupEntriesResults ---
@interface AuthUserServiceGroupEntriesResults : NSObject
@property (nonatomic, strong) NSArray * Entries;
@property (nonatomic, strong) NSError * Err;
@end

// --- MyFeedEntriesParams ---
@interface AuthUserServiceMyFeedEntriesParams : NSObject
@property (nonatomic, strong) NSString * EntryType;
@property (nonatomic, strong) NSString * Before;
@property (nonatomic, strong) NSNumber * Limit;
@end

// --- MyFeedEntriesResults ---
@interface AuthUserServiceMyFeedEntriesResults : NSObject
@property (nonatomic, strong) NSArray * Entries;
@property (nonatomic, strong) NSError * Err;
@end

// --- NewFeedEntriesParams ---
@interface AuthUserServiceNewFeedEntriesParams : NSObject
@property (nonatomic, strong) NSString * EntryType;
@property (nonatomic, strong) NSString * From;
@property (nonatomic, strong) NSNumber * Limit;
@end

// --- NewFeedEntriesResults ---
@interface AuthUserServiceNewFeedEntriesResults : NSObject
@property (nonatomic, strong) NSArray * Entries;
@property (nonatomic, strong) NSError * Err;
@end

// --- MyTaskEntriesParams ---
@interface AuthUserServiceMyTaskEntriesParams : NSObject
@property (nonatomic, assign) BOOL Active;
@property (nonatomic, strong) NSString * Before;
@property (nonatomic, strong) NSNumber * Limit;
@end

// --- MyTaskEntriesResults ---
@interface AuthUserServiceMyTaskEntriesResults : NSObject
@property (nonatomic, strong) NSArray * TasksForMe;
@property (nonatomic, strong) NSArray * MyCreatedTasks;
@property (nonatomic, strong) NSError * Err;
@end

// --- UserEntriesParams ---
@interface AuthUserServiceUserEntriesParams : NSObject
@property (nonatomic, strong) NSString * UserId;
@property (nonatomic, strong) NSString * EntryType;
@property (nonatomic, strong) NSString * Before;
@property (nonatomic, strong) NSNumber * Limit;
@end

// --- UserEntriesResults ---
@interface AuthUserServiceUserEntriesResults : NSObject
@property (nonatomic, strong) NSArray * Entries;
@property (nonatomic, strong) NSError * Err;
@end

// --- MyChatEntriesParams ---
@interface AuthUserServiceMyChatEntriesParams : NSObject
@property (nonatomic, strong) NSString * Before;
@property (nonatomic, strong) NSNumber * Limit;
@end

// --- MyChatEntriesResults ---
@interface AuthUserServiceMyChatEntriesResults : NSObject
@property (nonatomic, strong) NSArray * Entries;
@property (nonatomic, strong) NSError * Err;
@end

// --- MyNotificationItemsParams ---
@interface AuthUserServiceMyNotificationItemsParams : NSObject
@property (nonatomic, strong) NSString * Before;
@property (nonatomic, strong) NSNumber * Limit;
@end

// --- MyNotificationItemsResults ---
@interface AuthUserServiceMyNotificationItemsResults : NSObject
@property (nonatomic, strong) NSArray * NotificationItems;
@property (nonatomic, strong) NSError * Err;
@end

// --- MarkAllAsReadParams ---
@interface AuthUserServiceMarkAllAsReadParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@end

// --- MarkAllAsReadResults ---
@interface AuthUserServiceMarkAllAsReadResults : NSObject
@property (nonatomic, strong) MyCount * Mycount;
@property (nonatomic, strong) NSError * Err;
@end

// --- GetWatchListParams ---
@interface AuthUserServiceGetWatchListParams : NSObject
@property (nonatomic, strong) NSDate * Before;
@property (nonatomic, strong) NSNumber * Limit;
@end

// --- GetWatchListResults ---
@interface AuthUserServiceGetWatchListResults : NSObject
@property (nonatomic, strong) WatchList * Watchlist;
@property (nonatomic, strong) NSError * Err;
@end

// --- AddToWatchListParams ---
@interface AuthUserServiceAddToWatchListParams : NSObject
@property (nonatomic, strong) NSString * EntryId;
@property (nonatomic, strong) NSString * GroupId;
@end

// --- AddToWatchListResults ---
@interface AuthUserServiceAddToWatchListResults : NSObject
@property (nonatomic, assign) BOOL Added;
@property (nonatomic, strong) NSError * Err;
@end

// --- StopWatchingParams ---
@interface AuthUserServiceStopWatchingParams : NSObject
@property (nonatomic, strong) NSString * EntryId;
@property (nonatomic, strong) NSString * GroupId;
@end

// --- StopWatchingResults ---
@interface AuthUserServiceStopWatchingResults : NSObject
@property (nonatomic, assign) BOOL Stopped;
@property (nonatomic, strong) NSError * Err;
@end

// --- ReadWatchingParams ---
@interface AuthUserServiceReadWatchingParams : NSObject
@property (nonatomic, strong) NSString * EntryId;
@property (nonatomic, strong) NSString * GroupId;
@end

// --- ReadWatchingResults ---
@interface AuthUserServiceReadWatchingResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- UpdateLikeParams ---
@interface AuthUserServiceUpdateLikeParams : NSObject
@property (nonatomic, strong) LikeInput * Input;
@end

// --- UpdateLikeResults ---
@interface AuthUserServiceUpdateLikeResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) NSError * Err;
@end

// --- GetDraftListParams ---
@interface AuthUserServiceGetDraftListParams : NSObject
@property (nonatomic, strong) NSDate * Before;
@property (nonatomic, strong) NSNumber * Limit;
@end

// --- GetDraftListResults ---
@interface AuthUserServiceGetDraftListResults : NSObject
@property (nonatomic, strong) DraftList * Draftlist;
@property (nonatomic, strong) NSError * Err;
@end

// --- GetDraftParams ---
@interface AuthUserServiceGetDraftParams : NSObject
@property (nonatomic, strong) NSString * EntryId;
@property (nonatomic, strong) NSString * GroupId;
@end

// --- GetDraftResults ---
@interface AuthUserServiceGetDraftResults : NSObject
@property (nonatomic, strong) Entry * Entry;
@property (nonatomic, strong) NSError * Err;
@end

// --- DeleteDraftParams ---
@interface AuthUserServiceDeleteDraftParams : NSObject
@property (nonatomic, strong) NSString * EntryId;
@property (nonatomic, strong) NSString * GroupId;
@end

// --- DeleteDraftResults ---
@interface AuthUserServiceDeleteDraftResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- NewGroupParams ---
@interface AuthUserServiceNewGroupParams : NSObject
@end

// --- NewGroupResults ---
@interface AuthUserServiceNewGroupResults : NSObject
@property (nonatomic, strong) Group * Group;
@property (nonatomic, strong) NSError * Err;
@end

// --- GetGroupParams ---
@interface AuthUserServiceGetGroupParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@end

// --- GetGroupResults ---
@interface AuthUserServiceGetGroupResults : NSObject
@property (nonatomic, strong) Group * Group;
@property (nonatomic, strong) NSError * Err;
@end

// --- CreateGroupParams ---
@interface AuthUserServiceCreateGroupParams : NSObject
@property (nonatomic, strong) GroupInput * Input;
@end

// --- CreateGroupResults ---
@interface AuthUserServiceCreateGroupResults : NSObject
@property (nonatomic, strong) Group * Group;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- UpdateGroupParams ---
@interface AuthUserServiceUpdateGroupParams : NSObject
@property (nonatomic, strong) GroupInput * Input;
@end

// --- UpdateGroupResults ---
@interface AuthUserServiceUpdateGroupResults : NSObject
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- UpdateGroupLogoParams ---
@interface AuthUserServiceUpdateGroupLogoParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * LogoURL;
@end

// --- UpdateGroupLogoResults ---
@interface AuthUserServiceUpdateGroupLogoResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- DeleteGroupParams ---
@interface AuthUserServiceDeleteGroupParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@end

// --- DeleteGroupResults ---
@interface AuthUserServiceDeleteGroupResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- GroupBySlugParams ---
@interface AuthUserServiceGroupBySlugParams : NSObject
@property (nonatomic, strong) NSString * Slug;
@end

// --- GroupBySlugResults ---
@interface AuthUserServiceGroupBySlugResults : NSObject
@property (nonatomic, strong) Group * Group;
@property (nonatomic, strong) NSError * Err;
@end

// --- GetAllGroupsParams ---
@interface AuthUserServiceGetAllGroupsParams : NSObject
@property (nonatomic, strong) NSString * Keyword;
@end

// --- GetAllGroupsResults ---
@interface AuthUserServiceGetAllGroupsResults : NSObject
@property (nonatomic, strong) NSArray * Groups;
@property (nonatomic, strong) NSError * Err;
@end

// --- GetPublicGroupsParams ---
@interface AuthUserServiceGetPublicGroupsParams : NSObject
@property (nonatomic, strong) NSString * Keyword;
@end

// --- GetPublicGroupsResults ---
@interface AuthUserServiceGetPublicGroupsResults : NSObject
@property (nonatomic, strong) NSArray * Groups;
@property (nonatomic, strong) NSError * Err;
@end

// --- AddUserToGroupParams ---
@interface AuthUserServiceAddUserToGroupParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * UserId;
@end

// --- AddUserToGroupResults ---
@interface AuthUserServiceAddUserToGroupResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- RemoveUserFromGroupParams ---
@interface AuthUserServiceRemoveUserFromGroupParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * UserId;
@end

// --- RemoveUserFromGroupResults ---
@interface AuthUserServiceRemoveUserFromGroupResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- GetGroupHeaderItemParams ---
@interface AuthUserServiceGetGroupHeaderItemParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@end

// --- GetGroupHeaderItemResults ---
@interface AuthUserServiceGetGroupHeaderItemResults : NSObject
@property (nonatomic, strong) GroupHeaderItem * Ghi;
@property (nonatomic, strong) NSError * Err;
@end

// --- ClassifyMyGroupsParams ---
@interface AuthUserServiceClassifyMyGroupsParams : NSObject
@end

// --- ClassifyMyGroupsResults ---
@interface AuthUserServiceClassifyMyGroupsResults : NSObject
@property (nonatomic, strong) Group * PublicGroup;
@property (nonatomic, strong) NSArray * FollowedGroups;
@property (nonatomic, strong) NSArray * UnFollowedGroups;
@property (nonatomic, strong) NSError * Err;
@end

// --- OrganizationUsersParams ---
@interface AuthUserServiceOrganizationUsersParams : NSObject
@property (nonatomic, strong) NSString * Query;
@property (nonatomic, strong) NSString * SortKey;
@property (nonatomic, strong) NSNumber * CountPerPage;
@end

// --- OrganizationUsersResults ---
@interface AuthUserServiceOrganizationUsersResults : NSObject
@property (nonatomic, strong) NSArray * Users;
@property (nonatomic, strong) NSString * NewSortKey;
@property (nonatomic, strong) NSError * Err;
@end

// --- GroupUsersParams ---
@interface AuthUserServiceGroupUsersParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * Query;
@property (nonatomic, assign) BOOL OnlyFollowers;
@property (nonatomic, strong) NSString * SortKey;
@property (nonatomic, strong) NSNumber * CountPerPage;
@end

// --- GroupUsersResults ---
@interface AuthUserServiceGroupUsersResults : NSObject
@property (nonatomic, strong) NSArray * Users;
@property (nonatomic, strong) NSString * NewSortKey;
@property (nonatomic, strong) NSError * Err;
@end

// --- GetUserParams ---
@interface AuthUserServiceGetUserParams : NSObject
@property (nonatomic, strong) NSString * UserId;
@end

// --- GetUserResults ---
@interface AuthUserServiceGetUserResults : NSObject
@property (nonatomic, strong) User * User;
@property (nonatomic, strong) NSError * Err;
@end

// --- EnableUserParams ---
@interface AuthUserServiceEnableUserParams : NSObject
@property (nonatomic, strong) NSString * UserId;
@end

// --- EnableUserResults ---
@interface AuthUserServiceEnableUserResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- DisableUserParams ---
@interface AuthUserServiceDisableUserParams : NSObject
@property (nonatomic, strong) NSString * UserId;
@end

// --- DisableUserResults ---
@interface AuthUserServiceDisableUserResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- DeleteUserParams ---
@interface AuthUserServiceDeleteUserParams : NSObject
@property (nonatomic, strong) NSString * UserId;
@end

// --- DeleteUserResults ---
@interface AuthUserServiceDeleteUserResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- PromoteToSuperUserParams ---
@interface AuthUserServicePromoteToSuperUserParams : NSObject
@property (nonatomic, strong) NSString * UserId;
@end

// --- PromoteToSuperUserResults ---
@interface AuthUserServicePromoteToSuperUserResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- DemoteFromSuperUserParams ---
@interface AuthUserServiceDemoteFromSuperUserParams : NSObject
@property (nonatomic, strong) NSString * UserId;
@end

// --- DemoteFromSuperUserResults ---
@interface AuthUserServiceDemoteFromSuperUserResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- FollowUserParams ---
@interface AuthUserServiceFollowUserParams : NSObject
@property (nonatomic, strong) NSString * UserId;
@end

// --- FollowUserResults ---
@interface AuthUserServiceFollowUserResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- UnfollowUserParams ---
@interface AuthUserServiceUnfollowUserParams : NSObject
@property (nonatomic, strong) NSString * UserId;
@end

// --- UnfollowUserResults ---
@interface AuthUserServiceUnfollowUserResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- MyFollowingUsersParams ---
@interface AuthUserServiceMyFollowingUsersParams : NSObject
@end

// --- MyFollowingUsersResults ---
@interface AuthUserServiceMyFollowingUsersResults : NSObject
@property (nonatomic, strong) NSArray * FollowingPeople;
@property (nonatomic, strong) NSError * Err;
@end

// --- PanelStatusParams ---
@interface AuthUserServicePanelStatusParams : NSObject
@end

// --- PanelStatusResults ---
@interface AuthUserServicePanelStatusResults : NSObject
@property (nonatomic, strong) PanelStatus * PanelStatus;
@property (nonatomic, strong) NSError * Err;
@end

// --- PreferencesParams ---
@interface AuthUserServicePreferencesParams : NSObject
@end

// --- PreferencesResults ---
@interface AuthUserServicePreferencesResults : NSObject
@property (nonatomic, strong) Preferences * Preference;
@property (nonatomic, strong) NSError * Err;
@end

// --- UpdatePreferencesParams ---
@interface AuthUserServiceUpdatePreferencesParams : NSObject
@property (nonatomic, strong) PreferencesInput * Input;
@end

// --- UpdatePreferencesResults ---
@interface AuthUserServiceUpdatePreferencesResults : NSObject
@property (nonatomic, strong) Preferences * Preference;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- AllEmbedUsersParams ---
@interface AuthUserServiceAllEmbedUsersParams : NSObject
@end

// --- AllEmbedUsersResults ---
@interface AuthUserServiceAllEmbedUsersResults : NSObject
@property (nonatomic, strong) NSArray * Users;
@property (nonatomic, strong) NSError * Err;
@end

// --- GroupEmbedUsersParams ---
@interface AuthUserServiceGroupEmbedUsersParams : NSObject
@end

// --- GroupEmbedUsersResults ---
@interface AuthUserServiceGroupEmbedUsersResults : NSObject
@property (nonatomic, strong) NSArray * GroupUsers;
@property (nonatomic, strong) NSError * Err;
@end

// --- UpdateUserProfileParams ---
@interface AuthUserServiceUpdateUserProfileParams : NSObject
@property (nonatomic, strong) UserProfileInput * Input;
@end

// --- UpdateUserProfileResults ---
@interface AuthUserServiceUpdateUserProfileResults : NSObject
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- MyCountParams ---
@interface AuthUserServiceMyCountParams : NSObject
@end

// --- MyCountResults ---
@interface AuthUserServiceMyCountResults : NSObject
@property (nonatomic, strong) MyCount * MyCount;
@property (nonatomic, strong) NSError * Err;
@end

// --- ReadEntryParams ---
@interface AuthUserServiceReadEntryParams : NSObject
@property (nonatomic, strong) NSString * EntryId;
@property (nonatomic, strong) NSString * GroupId;
@end

// --- ReadEntryResults ---
@interface AuthUserServiceReadEntryResults : NSObject
@property (nonatomic, strong) MyCount * MyCount;
@property (nonatomic, strong) NSError * Err;
@end

// --- GetInvitationsInfoParams ---
@interface AuthUserServiceGetInvitationsInfoParams : NSObject
@end

// --- GetInvitationsInfoResults ---
@interface AuthUserServiceGetInvitationsInfoResults : NSObject
@property (nonatomic, strong) NSArray * Invitaions;
@property (nonatomic, strong) NSError * Err;
@end

// --- OrganizationsInfoParams ---
@interface AuthUserServiceOrganizationsInfoParams : NSObject
@property (nonatomic, strong) NSArray * OrgIds;
@end

// --- OrganizationsInfoResults ---
@interface AuthUserServiceOrganizationsInfoResults : NSObject
@property (nonatomic, strong) NSArray * Orgs;
@property (nonatomic, strong) NSError * Err;
@end

// --- OrganizationInfoParams ---
@interface AuthUserServiceOrganizationInfoParams : NSObject
@property (nonatomic, strong) NSString * OrgId;
@end

// --- OrganizationInfoResults ---
@interface AuthUserServiceOrganizationInfoResults : NSObject
@property (nonatomic, strong) Organization * Org;
@property (nonatomic, strong) NSError * Err;
@end

// --- SearchOrganizationsParams ---
@interface AuthUserServiceSearchOrganizationsParams : NSObject
@property (nonatomic, strong) NSString * Query;
@end

// --- SearchOrganizationsResults ---
@interface AuthUserServiceSearchOrganizationsResults : NSObject
@property (nonatomic, strong) NSArray * Org;
@property (nonatomic, strong) NSError * Err;
@end

// --- UpdateOrganizationParams ---
@interface AuthUserServiceUpdateOrganizationParams : NSObject
@property (nonatomic, strong) OrganizationInput * Input;
@end

// --- UpdateOrganizationResults ---
@interface AuthUserServiceUpdateOrganizationResults : NSObject
@property (nonatomic, strong) Organization * Org;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- SwitchOrganizationParams ---
@interface AuthUserServiceSwitchOrganizationParams : NSObject
@property (nonatomic, strong) NSString * OrgId;
@end

// --- SwitchOrganizationResults ---
@interface AuthUserServiceSwitchOrganizationResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- AcceptSharedGroupRequestParams ---
@interface AuthUserServiceAcceptSharedGroupRequestParams : NSObject
@property (nonatomic, strong) NSString * FromOrgId;
@property (nonatomic, strong) NSString * SharedOrgId;
@property (nonatomic, strong) NSString * SharedGroupId;
@property (nonatomic, strong) NSString * FromUserId;
@end

// --- AcceptSharedGroupRequestResults ---
@interface AuthUserServiceAcceptSharedGroupRequestResults : NSObject
@property (nonatomic, strong) Request * Req;
@property (nonatomic, strong) NSError * Err;
@end

// --- RejectSharedGroupRequestParams ---
@interface AuthUserServiceRejectSharedGroupRequestParams : NSObject
@property (nonatomic, strong) NSString * FromOrgId;
@property (nonatomic, strong) NSString * SharedOrgIdHex;
@property (nonatomic, strong) NSString * SharedGroupIdHex;
@property (nonatomic, strong) NSString * FromUserId;
@end

// --- RejectSharedGroupRequestResults ---
@interface AuthUserServiceRejectSharedGroupRequestResults : NSObject
@property (nonatomic, strong) Request * Req;
@property (nonatomic, strong) NSError * Err;
@end

// --- GetOrgSettingsParams ---
@interface AuthUserServiceGetOrgSettingsParams : NSObject
@end

// --- GetOrgSettingsResults ---
@interface AuthUserServiceGetOrgSettingsResults : NSObject
@property (nonatomic, strong) OrgSettings * OrgSetting;
@property (nonatomic, strong) NSError * Err;
@end

// --- UpdateOrgSettingsParams ---
@interface AuthUserServiceUpdateOrgSettingsParams : NSObject
@property (nonatomic, strong) OrgSettingsInput * OrgSettingInput;
@end

// --- UpdateOrgSettingsResults ---
@interface AuthUserServiceUpdateOrgSettingsResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- CanCreateGroupParams ---
@interface AuthUserServiceCanCreateGroupParams : NSObject
@end

// --- CanCreateGroupResults ---
@interface AuthUserServiceCanCreateGroupResults : NSObject
@property (nonatomic, assign) BOOL R;
@property (nonatomic, strong) NSError * Err;
@end

// --- CanInvitePeopleParams ---
@interface AuthUserServiceCanInvitePeopleParams : NSObject
@end

// --- CanInvitePeopleResults ---
@interface AuthUserServiceCanInvitePeopleResults : NSObject
@property (nonatomic, assign) BOOL R;
@property (nonatomic, strong) NSError * Err;
@end

// --- InvitePeopleParams ---
@interface AuthUserServiceInvitePeopleParams : NSObject
@property (nonatomic, strong) NSArray * Emails;
@end

// --- InvitePeopleResults ---
@interface AuthUserServiceInvitePeopleResults : NSObject
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- CancelInvitationParams ---
@interface AuthUserServiceCancelInvitationParams : NSObject
@property (nonatomic, strong) NSString * Email;
@end

// --- CancelInvitationResults ---
@interface AuthUserServiceCancelInvitationResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- ResendInvitationParams ---
@interface AuthUserServiceResendInvitationParams : NSObject
@property (nonatomic, strong) NSString * Email;
@end

// --- ResendInvitationResults ---
@interface AuthUserServiceResendInvitationResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- PrepareChangeEmailParams ---
@interface AuthUserServicePrepareChangeEmailParams : NSObject
@property (nonatomic, strong) NSString * NewEmail;
@end

// --- PrepareChangeEmailResults ---
@interface AuthUserServicePrepareChangeEmailResults : NSObject
@property (nonatomic, strong) EmailChanger * R;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- ChangeEmailParams ---
@interface AuthUserServiceChangeEmailParams : NSObject
@property (nonatomic, strong) NSString * Token;
@end

// --- ChangeEmailResults ---
@interface AuthUserServiceChangeEmailResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- UpdateAccountParams ---
@interface AuthUserServiceUpdateAccountParams : NSObject
@property (nonatomic, strong) MemberAccountInput * Input;
@end

// --- UpdateAccountResults ---
@interface AuthUserServiceUpdateAccountResults : NSObject
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- SendSharingInvitationParams ---
@interface AuthUserServiceSendSharingInvitationParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * Email;
@property (nonatomic, assign) BOOL IsResend;
@end

// --- SendSharingInvitationResults ---
@interface AuthUserServiceSendSharingInvitationResults : NSObject
@property (nonatomic, strong) SharingInvitationItem * Si;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end

// --- GetSharingInvitationItemsParams ---
@interface AuthUserServiceGetSharingInvitationItemsParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@end

// --- GetSharingInvitationItemsResults ---
@interface AuthUserServiceGetSharingInvitationItemsResults : NSObject
@property (nonatomic, strong) NSArray * Sis;
@property (nonatomic, strong) NSError * Err;
@end

// --- CancelSharingParams ---
@interface AuthUserServiceCancelSharingParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * Email;
@end

// --- CancelSharingResults ---
@interface AuthUserServiceCancelSharingResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- StopSharingGroupParams ---
@interface AuthUserServiceStopSharingGroupParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@property (nonatomic, strong) NSString * ToStopOrgId;
@end

// --- StopSharingGroupResults ---
@interface AuthUserServiceStopSharingGroupResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- LeaveSharingGroupParams ---
@interface AuthUserServiceLeaveSharingGroupParams : NSObject
@property (nonatomic, strong) NSString * GroupId;
@end

// --- LeaveSharingGroupResults ---
@interface AuthUserServiceLeaveSharingGroupResults : NSObject
@property (nonatomic, strong) NSError * Err;
@end

// --- ShareChatParams ---
@interface AuthUserServiceShareChatParams : NSObject
@property (nonatomic, strong) ShareChatInput * Input;
@end

// --- ShareChatResults ---
@interface AuthUserServiceShareChatResults : NSObject
@property (nonatomic, strong) Entry * ChatEntry;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end


@interface AuthUserService : NSObject
@property (nonatomic, strong) NSString * Session;


- (AuthUserServiceNewEntryResults *) NewEntry:(NSString *)groupId;

- (AuthUserServiceQortexMessagesResults *) QortexMessages:(NSString *)messsageType before:(NSString *)before limit:(NSNumber *)limit;

- (AuthUserServiceCreateBroadcastResults *) CreateBroadcast:(BroadcastInput *)input;

- (AuthUserServiceCreateBroadcastCommentResults *) CreateBroadcastComment:(BroadcastInput *)input;

- (AuthUserServiceGetRequestResults *) GetRequest:(NSString *)entryId;

- (AuthUserServiceEditBroadcastResults *) EditBroadcast:(NSString *)entryId;

- (AuthUserServiceEditBroadcastCommentResults *) EditBroadcastComment:(NSString *)entryId;

- (AuthUserServiceUpdateBroadcastResults *) UpdateBroadcast:(BroadcastInput *)input;

- (AuthUserServiceUpdateBroadcastCommentResults *) UpdateBroadcastComment:(BroadcastInput *)input;

- (AuthUserServiceCreatePostResults *) CreatePost:(EntryInput *)input;

- (AuthUserServiceCreateTaskResults *) CreateTask:(EntryInput *)input;

- (AuthUserServiceCloseTaskResults *) CloseTask:(NSString *)entryId groupId:(NSString *)groupId;

- (AuthUserServiceCreateCommentResults *) CreateComment:(EntryInput *)input;

- (AuthUserServiceGetCommentResults *) GetComment:(NSString *)entryId groupId:(NSString *)groupId;

- (AuthUserServiceUpdateCommentResults *) UpdateComment:(EntryInput *)input;

- (AuthUserServiceUpdateEntryResults *) UpdateEntry:(EntryInput *)input;

- (AuthUserServiceGetLatestUpdatedEntryIdByTitleResults *) GetLatestUpdatedEntryIdByTitle:(NSString *)title groupId:(NSString *)groupId;

- (AuthUserServiceGetEntryResults *) GetEntry:(NSString *)entryId groupId:(NSString *)groupId updateAtUnixNano:(NSString *)updateAtUnixNano searchKeyWords:(NSString *)searchKeyWords;

- (AuthUserServiceDeleteEntryResults *) DeleteEntry:(NSString *)entryId groupId:(NSString *)groupId dType:(NSString *)dType;

- (AuthUserServiceEntryAttachmentsResults *) EntryAttachments:(NSString *)entryId groupId:(NSString *)groupId;

- (AuthUserServiceOtherCommentsResults *) OtherComments:(NSString *)entryId groupId:(NSString *)groupId versionUpdateat:(NSString *)versionUpdateat searchKeyWords:(NSString *)searchKeyWords;

- (AuthUserServiceGroupEntriesResults *) GroupEntries:(NSString *)groupId entryType:(NSString *)entryType before:(NSString *)before limit:(NSNumber *)limit;

- (AuthUserServiceMyFeedEntriesResults *) MyFeedEntries:(NSString *)entryType before:(NSString *)before limit:(NSNumber *)limit;

- (AuthUserServiceNewFeedEntriesResults *) NewFeedEntries:(NSString *)entryType From:(NSString *)From limit:(NSNumber *)limit;

- (AuthUserServiceMyTaskEntriesResults *) MyTaskEntries:(BOOL)active before:(NSString *)before limit:(NSNumber *)limit;

- (AuthUserServiceUserEntriesResults *) UserEntries:(NSString *)userId entryType:(NSString *)entryType before:(NSString *)before limit:(NSNumber *)limit;

- (AuthUserServiceMyChatEntriesResults *) MyChatEntries:(NSString *)before limit:(NSNumber *)limit;

- (AuthUserServiceMyNotificationItemsResults *) MyNotificationItems:(NSString *)before limit:(NSNumber *)limit;

- (AuthUserServiceMarkAllAsReadResults *) MarkAllAsRead:(NSString *)groupId;

- (AuthUserServiceGetWatchListResults *) GetWatchList:(NSDate *)before limit:(NSNumber *)limit;

- (AuthUserServiceAddToWatchListResults *) AddToWatchList:(NSString *)entryId groupId:(NSString *)groupId;

- (AuthUserServiceStopWatchingResults *) StopWatching:(NSString *)entryId groupId:(NSString *)groupId;

- (AuthUserServiceReadWatchingResults *) ReadWatching:(NSString *)entryId groupId:(NSString *)groupId;

- (AuthUserServiceUpdateLikeResults *) UpdateLike:(LikeInput *)input;

- (AuthUserServiceGetDraftListResults *) GetDraftList:(NSDate *)before limit:(NSNumber *)limit;

- (AuthUserServiceGetDraftResults *) GetDraft:(NSString *)entryId groupId:(NSString *)groupId;

- (AuthUserServiceDeleteDraftResults *) DeleteDraft:(NSString *)entryId groupId:(NSString *)groupId;

- (AuthUserServiceNewGroupResults *) NewGroup;

- (AuthUserServiceGetGroupResults *) GetGroup:(NSString *)groupId;

- (AuthUserServiceCreateGroupResults *) CreateGroup:(GroupInput *)input;

- (AuthUserServiceUpdateGroupResults *) UpdateGroup:(GroupInput *)input;

- (AuthUserServiceUpdateGroupLogoResults *) UpdateGroupLogo:(NSString *)groupId logoURL:(NSString *)logoURL;

- (AuthUserServiceDeleteGroupResults *) DeleteGroup:(NSString *)groupId;

- (AuthUserServiceGroupBySlugResults *) GroupBySlug:(NSString *)slug;

- (AuthUserServiceGetAllGroupsResults *) GetAllGroups:(NSString *)keyword;

- (AuthUserServiceGetPublicGroupsResults *) GetPublicGroups:(NSString *)keyword;

- (AuthUserServiceAddUserToGroupResults *) AddUserToGroup:(NSString *)groupId userId:(NSString *)userId;

- (AuthUserServiceRemoveUserFromGroupResults *) RemoveUserFromGroup:(NSString *)groupId userId:(NSString *)userId;

- (AuthUserServiceGetGroupHeaderItemResults *) GetGroupHeaderItem:(NSString *)groupId;

- (AuthUserServiceClassifyMyGroupsResults *) ClassifyMyGroups;

- (AuthUserServiceOrganizationUsersResults *) OrganizationUsers:(NSString *)query sortKey:(NSString *)sortKey countPerPage:(NSNumber *)countPerPage;

- (AuthUserServiceGroupUsersResults *) GroupUsers:(NSString *)groupId query:(NSString *)query OnlyFollowers:(BOOL)OnlyFollowers sortKey:(NSString *)sortKey countPerPage:(NSNumber *)countPerPage;

- (AuthUserServiceGetUserResults *) GetUser:(NSString *)userId;

- (AuthUserServiceEnableUserResults *) EnableUser:(NSString *)userId;

- (AuthUserServiceDisableUserResults *) DisableUser:(NSString *)userId;

- (AuthUserServiceDeleteUserResults *) DeleteUser:(NSString *)userId;

- (AuthUserServicePromoteToSuperUserResults *) PromoteToSuperUser:(NSString *)userId;

- (AuthUserServiceDemoteFromSuperUserResults *) DemoteFromSuperUser:(NSString *)userId;

- (AuthUserServiceFollowUserResults *) FollowUser:(NSString *)userId;

- (AuthUserServiceUnfollowUserResults *) UnfollowUser:(NSString *)userId;

- (AuthUserServiceMyFollowingUsersResults *) MyFollowingUsers;

- (AuthUserServicePanelStatusResults *) PanelStatus;

- (AuthUserServicePreferencesResults *) Preferences;

- (AuthUserServiceUpdatePreferencesResults *) UpdatePreferences:(PreferencesInput *)input;

- (AuthUserServiceAllEmbedUsersResults *) AllEmbedUsers;

- (AuthUserServiceGroupEmbedUsersResults *) GroupEmbedUsers;

- (AuthUserServiceUpdateUserProfileResults *) UpdateUserProfile:(UserProfileInput *)input;

- (AuthUserServiceMyCountResults *) MyCount;

- (AuthUserServiceReadEntryResults *) ReadEntry:(NSString *)entryId groupId:(NSString *)groupId;

- (AuthUserServiceGetInvitationsInfoResults *) GetInvitationsInfo;

- (AuthUserServiceOrganizationsInfoResults *) OrganizationsInfo:(NSArray *)orgIds;

- (AuthUserServiceOrganizationInfoResults *) OrganizationInfo:(NSString *)orgId;

- (AuthUserServiceSearchOrganizationsResults *) SearchOrganizations:(NSString *)query;

- (AuthUserServiceUpdateOrganizationResults *) UpdateOrganization:(OrganizationInput *)input;

- (AuthUserServiceSwitchOrganizationResults *) SwitchOrganization:(NSString *)orgId;

- (AuthUserServiceAcceptSharedGroupRequestResults *) AcceptSharedGroupRequest:(NSString *)fromOrgId sharedOrgId:(NSString *)sharedOrgId sharedGroupId:(NSString *)sharedGroupId fromUserId:(NSString *)fromUserId;

- (AuthUserServiceRejectSharedGroupRequestResults *) RejectSharedGroupRequest:(NSString *)fromOrgId sharedOrgIdHex:(NSString *)sharedOrgIdHex sharedGroupIdHex:(NSString *)sharedGroupIdHex fromUserId:(NSString *)fromUserId;

- (AuthUserServiceGetOrgSettingsResults *) GetOrgSettings;

- (AuthUserServiceUpdateOrgSettingsResults *) UpdateOrgSettings:(OrgSettingsInput *)orgSettingInput;

- (AuthUserServiceCanCreateGroupResults *) CanCreateGroup;

- (AuthUserServiceCanInvitePeopleResults *) CanInvitePeople;

- (AuthUserServiceInvitePeopleResults *) InvitePeople:(NSArray *)emails;

- (AuthUserServiceCancelInvitationResults *) CancelInvitation:(NSString *)email;

- (AuthUserServiceResendInvitationResults *) ResendInvitation:(NSString *)email;

- (AuthUserServicePrepareChangeEmailResults *) PrepareChangeEmail:(NSString *)newEmail;

- (AuthUserServiceChangeEmailResults *) ChangeEmail:(NSString *)token;

- (AuthUserServiceUpdateAccountResults *) UpdateAccount:(MemberAccountInput *)input;

- (AuthUserServiceSendSharingInvitationResults *) SendSharingInvitation:(NSString *)groupId email:(NSString *)email isResend:(BOOL)isResend;

- (AuthUserServiceGetSharingInvitationItemsResults *) GetSharingInvitationItems:(NSString *)groupId;

- (AuthUserServiceCancelSharingResults *) CancelSharing:(NSString *)groupId email:(NSString *)email;

- (AuthUserServiceStopSharingGroupResults *) StopSharingGroup:(NSString *)GroupId toStopOrgId:(NSString *)toStopOrgId;

- (AuthUserServiceLeaveSharingGroupResults *) LeaveSharingGroup:(NSString *)GroupId;

- (AuthUserServiceShareChatResults *) ShareChat:(ShareChatInput *)input;
@end


// --- GetSessionParams ---
@interface GlobalGetSessionParams : NSObject
@property (nonatomic, strong) NSString * Email;
@property (nonatomic, strong) NSString * Password;
@end

// --- GetSessionResults ---
@interface GlobalGetSessionResults : NSObject
@property (nonatomic, strong) NSString * Session;
@property (nonatomic, strong) Validated * Validated;
@property (nonatomic, strong) NSError * Err;
@end


@interface Global : NSObject

- (GlobalGetSessionResults *) GetSession:(NSString *)email password:(NSString *)password;

- (AuthUserService *) GetAuthUserService:(NSString *)session;
@end

