// Generated by github.com/sunfmin/goapigen
// DO NOT EDIT
#import "qortexapi.h"

// --- Organization ---
@implementation Organization
@synthesize Id = _Id;
@synthesize Name = _Name;
@synthesize QortexURL = _QortexURL;
@synthesize Summary = _Summary;
@synthesize LogoURL = _LogoURL;
@synthesize Address = _Address;
@synthesize Phone = _Phone;
@synthesize Website = _Website;
@synthesize Domains = _Domains;
@synthesize RestrictSubscriptionMail = _RestrictSubscriptionMail;
@end


// === Interfaces ===


@implementation AuthUserService : NSObject

@synthesize Session = _Session;


// --- OrganizationInfo ---
- (AuthUserServiceOrganizationInfoResults *) OrganizationInfo:(NSString *)orgId {
	
	AuthUserServiceOrganizationInfoResults *results = [[AuthUserServiceOrganizationInfoResults alloc] init];
	AuthUserServiceOrganizationInfoParams *params = [[AuthUserServiceOrganizationInfoParams alloc] init];
	[params setOrgId:orgId];
	
	//[DoRequest:params results:results];
	return results;
}
@end

@implementation Global : NSObject


// --- GetSession ---
- (GlobalGetSessionResults *) GetSession:(NSString *)email password:(NSString *)password {
	
	GlobalGetSessionResults *results = [[GlobalGetSessionResults alloc] init];
	GlobalGetSessionParams *params = [[GlobalGetSessionParams alloc] init];
	[params setEmail:email];
	[params setPassword:password];
	
	//[DoRequest:params results:results];
	return results;
}

// --- GetAuthUserService ---
- (AuthUserService *) GetAuthUserService:(NSString *)session {
	
	AuthUserService *results = [[AuthUserService alloc] init];
	[results setSession:session];
	
	//[DoRequest:params results:results];
	return results;
}
@end



